### ISSUE TITLE
Problem in MySQL Query while doing `/trails set`

### ISSUE THREAD

**Issue by Zoro-6191** [Oribuin/FlightTrails#2]
![image](https://user-images.githubusercontent.com/52291201/123778903-3ac98200-d8ef-11eb-8dd1-698bf4530a73.png)

Log: https://mcpaste.io/55552da473533b29

Paper 1.17#53

**Comment by Oribuin** [comment]
Will look into why the data migration hasn't ran. Try running this query manually [here](https://github.com/Oribuin/FlightTrails/blob/master/src/main/kotlin/xyz/oribuin/flighttrails/migration/ModifyTable.kt#L10)

**Comment by Zoro-6191** [comment]
that worked, doesnt give any more errors

**Comment by Oribuin** [comment]
It should be fixed now in the latest update for FlightTrails.
